# Generated by Django 2.2.1 on 2019-06-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_confirmstring_user'),
        ('confer_manage', '0007_auto_20190612_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_prepared',
            field=models.BooleanField(default=False, verbose_name='是否主动提交摘要'),
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(default='', max_length=200, verbose_name='收入事由')),
                ('money', models.FloatField(default=0.0, max_length=10, verbose_name='收入金额')),
                ('money_sub', models.FloatField(default=0.0, max_length=10, verbose_name='已交罚款金额')),
                ('is_money_sub', models.BooleanField(default=False, verbose_name='是否全部上交')),
                ('confer_apart', models.ForeignKey(default='', on_delete=django.db.models.deletion.ProtectedError, to='confer_manage.Apartment', verbose_name='所属部门')),
                ('income_confer', models.ForeignKey(default='', on_delete=django.db.models.deletion.ProtectedError, to='confer_manage.Conference', verbose_name='收入所属会议')),
                ('income_people', models.ForeignKey(default='', on_delete=django.db.models.deletion.ProtectedError, to='login.User', verbose_name='创建人员')),
            ],
            options={
                'verbose_name': '基金情况',
                'verbose_name_plural': '基金情况',
            },
        ),
    ]
